server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?characterEncoding=utf8&useSSL=false
    username: root
    password: Hf@173503494 # 服务器是 Hf@173503494
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10010/eureka

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印 MyBatis 日志
    map-underscore-to-camel-case: true # 配置驼峰自动转换
