server:
  port: 10030

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: order-service # 路由 id 随便起，只要不重复就刑
          uri: lb://order-service # 目标服务地址
          predicates:
            - Path=/order/** # 匹配条件，如果说满足 /order/** 这样的一个路径，就会转发到目标服务地址上